### ISSUE TITLE
binmode => utf8 throws a warning

### ISSUE THREAD

**Issue by foobargeez** [perhunter/slurp#21]
`syswrite() is deprecated on :utf8 handles. This will be a fatal error in Perl 5.30`

Can we default to 'utf8' and also open the file using I/O layers as opposed to sysopen, say, `:raw:encoding($encoding)`?

If you're OK with the idea, I will attempt a PR.

Thanks!

**Comment by genio** [comment]
Changing the default behavior is not likely to be accepted as this module is way too far up the CPAN river to make any backwards-compat breaking changes.  However, we're in the midst of a branch to fix the syswrite() problem another way:
https://github.com/perhunter/slurp/pull/22

**Comment by genio** [comment]
This is now resolved as v9999.26 has been released.
