### ISSUE TITLE
Do not create/touch file, if no data should be written.

### ISSUE THREAD

**Issue by XSven** [perhunter/slurp#27]
The following calls

```
perl -M'File::Slurp qw(write_file)' -e 'my @data=(); write_file(q(foo), @data);'   # empty @data array
perl -M'File::Slurp qw(write_file)' -e 'my @data=(''); write_file(q(foo), @data);' # empty string is 0th element of @data
```
have the same effect: They create an empty file _foo_, if it does not exist. I was not able to configure `write_file()` in a way that an empty `@data` array, does not create/touch a file. From my perspective this should be the case. I know that even if you are with me, you cannot change this inconsistent behaviour without breaking the backwards compatibility. Maybe it is possible to add an option **no_touch** that prevents the creation of a file, if no data should be written.

**Comment by karenetheridge** [comment]
Please, for the love of kittens, switch to Path::Tiny or File::Slurper. It is unlikely that features will be added to File::Slurp, and you can save yourself many headaches:

https://metacpan.org/pod/Perl::Critic::Policy::Freenode::DiscouragedModules#File::Slurp

**Comment by genio** [comment]
I agree with @karenetheridge that it is better to use one of the newer modules such as Path::Tiny or File::Slurper. However, in this case, it makes more sense to just not call `write_file()` when you don't have anything to write if you don't want an empty file to be created.

**Comment by XSven** [comment]
Thanks for the quick feedback and the recommendations!
