### ISSUE TITLE
Real Release?

### ISSUE THREAD

**Issue by genio** [perhunter/slurp#7]
There are a few bugs out there on the current release that prevent installation/use on 5.10 and below, particularly the `use 5.6.2;` bug. The current two dev releases have been testing well so far and contain no code changes other than the removal of that line. The version restriction is in `Makefile.PL` and uses the `use 5.006;` form, which will clear up that bug.

I'm proposing a release to be cut on Monday which will have given CPAN Testers several days to show any build failures. I believe we have cleaned up the test failures as well as the Perl version failure above and cleaned up the build as a whole. Cutting a more or less zero-code change release would allow us to ensure our test suite is good to go before moving on to substantive changes.

**Comment by genio** [comment]
@jkeenan Any thoughts on this plan?

**Comment by jkeenan** [comment]
> @jkeenan Any thoughts on this plan?

+1
